blogs/urls.py
from django.urls import path
from blogs.views import BlogsListView, BlogDetailsView

app_name = 'blogs'


urlpatterns = [
    path('', BlogsListView.as_view(), name='list'),
    path('details/<int:pk>/', BlogDetailsView.as_view(), name='details')
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from pages.views import HomePageView, ContactView, AboutView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about')
]

blogs/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models



class AuthorModel(models.Model):
    name = models.CharField(max_length=128)
    position = models.CharField(max_length=64)
    image = models.ImageField(upload_to='blog-author-images', default='default-images/admin-photo.png')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'


class BlogModel(models.Model):
    title = models.TextField()
    image = models.ImageField(upload_to='blog-photos', null=True)
    short_description = models.TextField()
    long_description = models.TextField()
    categories = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='blogs')
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE)
    test_editor = RichTextUploadingField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

blogs/views.py
from django.views.generic import TemplateView, ListView
from django.views.generic import TemplateView, ListView

from blogs.models import BlogModel, BlogTagModel, BlogCategoryModel


class BlogsListView(ListView):
    template_name = 'blogs/blogs-list.html'
    model = BlogModel
    context_object_name = 'blogs'
    paginate_by = 4

    def get_queryset(self):
        blogs = BlogModel.objects.all().order_by('created_at')
        tag = self.request.GET.get('tag')
        cat = self.request.GET.get('cat')
        if tag:
            blogs = blogs.filter(tags__in=tag)
        if cat:
            blogs = blogs.filter(categories__in=cat)

        return blogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = BlogCategoryModel.objects.all()
        context['tags'] = BlogTagModel.objects.all()
        blogs_data = self.get_queryset()
        context['recent_posts'] = blogs_data[:3]


        return context


class BlogDetailsView(TemplateView):
    template_name = 'blogs/blog-details.html'
    model = BlogModel

    def get_context_data(self, **kwargs):
        context = dict()
        context['categories'] = BlogCategoryModel.objects.all()
        context['tags'] = BlogTagModel.objects.all()
        context['recent_posts'] = BlogModel.objects.all().order_by('created_at')[:3]
        context['blog'] = BlogModel.objects.get(id=self.kwargs["pk"])

        return context

templates/blogs/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="body-wrapper">
    <!-- Begin Header Area -->
    {% include 'layouts/header-base.html' %}
    <!-- Header Area End Here -->
    <!-- Begin Li's Breadcrumb Area -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="breadcrumb-content">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Blog Details Left Sidebar</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Li's Breadcrumb Area End Here -->
    <!-- Begin Li's Main Blog Page Area -->
    <div class="li-main-blog-page li-main-blog-details-page pt-60 pb-60 pb-sm-45 pb-xs-45">
        <div class="container">
            <div class="row">
                <!-- Begin Li's Blog Sidebar Area -->
                {% include 'blogs/blogs-left-side.html' %}
                <!-- Li's Blog Sidebar Area End Here -->
                <!-- Begin Li's Main Content Area -->
                <div class="col-lg-9 order-lg-2 order-1">
                    <div class="row li-main-content">
                        <div class="col-lg-12">
                            <div class="li-blog-single-item pb-30">
                                <div class="li-blog-banner">
                                    <a href="blog-details.html"><img class="img-full"
                                                                     src="{{blog.image.url}}"
                                                                     alt=""></a>
                                </div>
                                <div class="li-blog-content">
                                    <div class="li-blog-details">
                                        <h3 class="li-blog-heading pt-25"><a href="#">{{blog.title}}</a></h3>
                                        <div class="li-blog-meta">
                                            <a class="author" href="#"><i class="fa fa-user"></i>{{blog.author.name}}</a>
                                            <a class="comment" href="#"><i class="fa fa-comment-o"></i> 3 comment</a>
                                            <a class="post-time" href="#"><i class="fa fa-calendar"></i> {{blog.created_at|date}}</a>
                                        </div>
                                        <p>{{blog.short_description}}</p>
                                        <!-- Begin Blog Blockquote Area -->
                                        <div class="li-blog-blockquote">
                                            <blockquote>
                                                <p>{{blog.long_description}}</p>
                                            </blockquote>
                                        </div>
                                        <!-- Blog Blockquote Area End Here -->
                                        <div class="li-tag-line">
                                            <h4>tag:</h4>
                                            {% for tag in tags %}
                                            <a href="{% url 'blogs:list' %}?tag={{tag.id}}">{{tag}}</a>{% if forloop.counter != tags.count %},{% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="li-blog-sharing text-center pt-30">
                                            <h4>share this post:</h4>
                                            <a href="#"><i class="fa fa-facebook"></i></a>
                                            <a href="#"><i class="fa fa-twitter"></i></a>
                                            <a href="#"><i class="fa fa-pinterest"></i></a>
                                            <a href="#"><i class="fa fa-google-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Begin Li's Blog Comment Section -->
                            <div class="li-comment-section">
                                <h3>03 comment</h3>
                                <ul>
                                    <li>
                                        <div class="author-avatar pt-15">
                                            <img src="{% static 'images/product-details/user.png' %}" alt="User">
                                        </div>
                                        <div class="comment-body pl-15">
                                            <span class="reply-btn pt-15 pt-xs-5"><a href="#">reply</a></span>
                                            <h5 class="comment-author pt-15">admin</h5>
                                            <div class="comment-post-date">
                                                20 nov, 2018 at 9:30pm
                                            </div>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim maiores
                                                adipisci optio ex, laboriosam facilis non pariatur itaque illo sunt?</p>
                                        </div>
                                    </li>
                                    <li class="comment-children">
                                        <div class="author-avatar pt-15">
                                            <img src="{% static 'images/product-details/admin.png' %}" alt="Admin">
                                        </div>
                                        <div class="comment-body pl-15">
                                            <span class="reply-btn pt-15 pt-xs-5"><a href="#">reply</a></span>
                                            <h5 class="comment-author pt-15">admin</h5>
                                            <div class="comment-post-date">
                                                20 nov, 2018 at 9:30pm
                                            </div>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim maiores
                                                adipisci optio ex, laboriosam facilis non pariatur itaque illo sunt?</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="author-avatar pt-15">
                                            <img src="{% static 'images/product-details/admin.png' %}" alt="Admin">
                                        </div>
                                        <div class="comment-body pl-15">
                                            <span class="reply-btn pt-15 pt-xs-5"><a href="#">reply</a></span>
                                            <h5 class="comment-author pt-15">admin</h5>
                                            <div class="comment-post-date">
                                                20 nov, 2018 at 9:30pm
                                            </div>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim maiores
                                                adipisci optio ex, laboriosam facilis non pariatur itaque illo sunt?</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- Li's Blog Comment Section End Here -->
                            <!-- Begin Blog comment Box Area -->
                            <div class="li-blog-comment-wrapper">
                                <h3>leave a reply</h3>
                                <p>Your email address will not be published. Required fields are marked *</p>
                                <form action="#">
                                    <div class="comment-post-box">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <label>comment</label>
                                                <textarea name="commnet" placeholder="Write a comment"></textarea>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 mt-5 mb-sm-20 mb-xs-20">
                                                <label>Name</label>
                                                <input type="text" class="coment-field" placeholder="Name">
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 mt-5 mb-sm-20 mb-xs-20">
                                                <label>Email</label>
                                                <input type="text" class="coment-field" placeholder="Email">
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 mt-5 mb-sm-20">
                                                <label>Website</label>
                                                <input type="text" class="coment-field" placeholder="Website">
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="coment-btn pt-30 pb-sm-30 pb-xs-30 f-left">
                                                    <input class="li-btn-2" type="submit" name="submit"
                                                           value="post comment">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <!-- Blog comment Box Area End Here -->
                        </div>
                    </div>
                </div>
                <!-- Li's Main Content Area End Here -->
            </div>
        </div>
    </div>
    <!-- Li's Main Blog Page Area End Here -->
    <!-- Begin Footer Area -->
        {% include 'layouts/footer-base.html' %}

    <!-- Footer Area End Here -->
</div>
{% endblock %}

templates/blogs/blogs-left-side.html
{% load static %}
<div class="col-lg-3 order-lg-1 order-2">
    <div class="li-blog-sidebar-wrapper">
        <div class="li-blog-sidebar">
            <div class="li-sidebar-search-form pt-xs-30 pt-sm-30">
                <form action="#">
                    <input type="text" class="li-search-field" placeholder="search here">
                    <button type="submit" class="li-search-btn"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
        <div class="li-blog-sidebar pt-25">
            <h4 class="li-blog-sidebar-title">Categories</h4>
            <ul class="li-blog-archive">
                {% for category in categories %}
                <li><a {% if 'blogs/details/' in request.path %}
                    href="{% url 'blogs:list' %}?cat={{category.id}}"
                    {% else %}
                    style="cursor:pointer" onclick="addUrlParameter('cat', {{category.id}})" {% endif%}> {{category}} ({{category.blogs.count}})</a></>
                {% endfor %}
            </ul>
        </div>
        <div class="li-blog-sidebar">
            <h4 class="li-blog-sidebar-title">Blog Archives</h4>
            <ul class="li-blog-archive">
                <li><a href="#">January (10)</a></li>
                <li><a href="#">February (08)</a></li>
                <li><a href="#">March (07)</a></li>
                <li><a href="#">April (14)</a></li>
                <li><a href="#">May (10)</a></li>
                <li><a href="#">June (06)</a></li>
            </ul>
        </div>
        <div class="li-blog-sidebar">
            <h4 class="li-blog-sidebar-title">Recent Post</h4>
            {% for recent_post in recent_posts %}

            <div class="li-recent-post pb-30">
                <div class="li-recent-post-thumb">
                    <a href="{% url 'blogs:details' pk=recent_post.id %}">
                        <img class="img-full" src="{{recent_post.image.url}}"
                             alt="{{recent_post.title}}">
                    </a>
                </div>
                <div class="li-recent-post-des">
                    <span><a href="{% url 'blogs:details' pk=recent_post.id %}">{{recent_post.title}}</a></span>
                    <span class="li-post-date">{{recent_post.created_at|date:"d.m.Y"}}</span>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="li-blog-sidebar">
            <h4 class="li-blog-sidebar-title">Tags</h4>
            <ul class="li-blog-tags">
                {% for tag in tags %}
                <li><a
                        {% if 'blogs/details/' in request.path %}
                    href="{% url 'blogs:list' %}?tag={{tag.id}}"
                    {% else %}
                    style="cursor:pointer" onclick="addUrlParameter('tag', {{tag.id}})" {% endif%}>
                    {{tag.name}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blogs/blogs-list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="body-wrapper">
    <!-- Begin Header Area -->
    {% include 'layouts/header-base.html' %}
    <!-- Header Area End Here -->
    <!-- Begin Li's Breadcrumb Area -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="breadcrumb-content">
                <ul>
                    <li><a href="{% url 'pages:home' %}">Home</a></li>
                    <li class="active">Blog List Left Sidebar</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Li's Breadcrumb Area End Here -->
    <!-- Begin Li's Main Blog Page Area -->
    <div class="li-main-blog-page pt-60 pb-55">
        <div class="container">
            <div class="row">
                <!-- Begin Li's Blog Sidebar Area -->
                {% include 'blogs/blogs-left-side.html' %}
                <!-- Li's Blog Sidebar Area End Here -->
                <!-- Begin Li's Main Content Area -->
                <div class="col-lg-9 order-lg-2 order-1">
                    <div class="row li-main-content">
                        {% for blog in blogs %}
                        <div class="col-lg-12">
                            <div class="li-blog-single-item mb-30">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="li-blog-banner">
                                            <a href="{% url 'blogs:details' pk=blog.id %}"><img class="img-full"
                                                                                          src="{{blog.image.url}}"
                                                                                          alt=""></a>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="li-blog-content">
                                            <div class="li-blog-details">
                                                <h3 class="li-blog-heading pt-xs-25 pt-sm-25"><a
                                                        href="{% url 'blogs:details' pk=blog.id %}">{{blog.title}}</a></h3>
                                                <div class="li-blog-meta">
                                                    <a class="author" href="#"><i class="fa fa-user"></i>{{blog.author.name}}</a>
                                                    <a class="comment" href="#"><i class="fa fa-comment-o"></i> 3
                                                        comment</a>
                                                    <a class="post-time" href="#"><i class="fa fa-calendar"></i> {{blog.created_at|date}}</a>
                                                </div>
                                                <p>{{blog.short_description}}</p>
                                                <a class="read-more" href="{% url 'blogs:details' pk=blog.id %}">Read
                                                    More...</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- Begin Li's Pagination Area -->
                        <div class="col-lg-12">
                            <div class="li-paginatoin-area text-center pt-25">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <ul class="li-pagination-box">
                                            {% if page_obj.has_previous %}
                                            <li><a class="Previous" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                                            {% endif %}
                                            {% for page in page_obj.paginator.page_range %}
                                            <li {% if page == page_obj.number %} class="active" {% endif %}><a href="?page={{page}}">{{page}}</a></li>
                                            {% endfor %}
                                            {% if page_obj.has_next %}
                                            <li><a class="Next" href="?page={{page_obj.next_page_number}}">Next</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Li's Pagination End Here Area -->
                    </div>
                </div>
                <!-- Li's Main Content Area End Here -->
            </div>
        </div>
    </div>
    <!-- Li's Main Blog Page Area End Here -->
    <!-- Begin Footer Area -->
    {% include 'layouts/footer-base.html' %}
    <!-- Footer Area End Here -->
</div>
{% endblock %}

{% block extra_js %}
<script>
    function addUrlParameter(name, value){
    let searchParams = new URLSearchParams(window. location.search)
    if (searchParams.has(name) && searchParams.get(name) === value) {
    searchParams. delete(name)
    } else {
    searchParams.set(name, value)
}
    window. location.search = searchParams.toString()
}
</script>
{% endblock %}